/**
 * Energy dispersal (PRBS descrambler) for ISDB-T (ARIB STD-B31).
 *
 * The scrambling sequence is generated by x^15 + x^14 + 1, initialised to
 * 100101010000000 (0x4a80). Every byte of the 204-byte RS codeword except the
 * sync byte is XORed bit-by-bit; the register is clocked eight times per byte,
 * including for the sync byte whose PRBS output is discarded.
 *
 * On air the sync byte (0x47) is transmitted last, so the descrambler rotates
 * it back to the front and returns the 204-byte RS codeword with the sync byte
 * at offset 0.
 */

export const TS_PACKET_SIZE = 188
export const RS_CODEWORD_SIZE = 204
export const SYNC_BYTE = 0x47

export const ENERGY_DISPERSAL_INIT = 0x4a80
const REGISTER_MASK = 0x7fff

export class EnergyDescrambler {
  private reg = ENERGY_DISPERSAL_INIT

  reset(): void {
    this.reg = ENERGY_DISPERSAL_INIT
  }

  private clock(count: number): number {
    let result = 0
    for (let i = 0; i < count; i++) {
      const feedback = ((this.reg >> 13) ^ (this.reg >> 14)) & 1
      this.reg = ((this.reg << 1) | feedback) & REGISTER_MASK
      result = (result << 1) | feedback
    }
    return result
  }

  /**
   * Descramble one 204-byte codeword. Input has the sync byte at the end;
   * output has it at offset 0.
   */
  processBlock(block: Uint8Array): Uint8Array {
    if (block.length !== RS_CODEWORD_SIZE) {
      throw new Error(`energy dispersal expects ${RS_CODEWORD_SIZE} bytes`)
    }
    const out = new Uint8Array(RS_CODEWORD_SIZE)
    out[0] = block[RS_CODEWORD_SIZE - 1]
    for (let j = 0; j < RS_CODEWORD_SIZE - 1; j++) {
      out[j + 1] = block[j] ^ this.clock(8)
    }
    this.clock(8)
    return out
  }
}
