#!/usr/bin/env node
/**
 * Build one or all Rust DSP kernels to wasm32 and embed the binary as a base64
 * TypeScript module so it can be loaded synchronously in workers, tests and the
 * browser without any asset/fetch plumbing.
 *
 * Usage:
 *   node scripts/build-wasm.mjs <crate>   # build wasm/<crate>
 *   node scripts/build-wasm.mjs --all     # build every wasm/* crate
 *
 * The generated file is `src/dsp/wasm/<crate>.bytes.ts` exporting `wasmBase64`.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const wasmDir = resolve(root, 'wasm')
const outDir = resolve(root, 'src/dsp/wasm')
const targetDir = resolve(wasmDir, 'target')

function crateName(dir) {
  const manifest = readFileSync(resolve(dir, 'Cargo.toml'), 'utf8')
  const match = manifest.match(/^\s*name\s*=\s*"([^"]+)"/m)
  if (!match) throw new Error(`no package name in ${dir}/Cargo.toml`)
  return match[1]
}

function build(name) {
  const dir = resolve(wasmDir, name)
  if (!existsSync(resolve(dir, 'Cargo.toml'))) {
    throw new Error(`unknown wasm crate: ${name}`)
  }
  execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown'], {
    cwd: dir,
    stdio: 'inherit',
    env: { ...process.env, CARGO_TARGET_DIR: targetDir },
  })

  const pkg = crateName(dir)
  const wasmPath = resolve(targetDir, 'wasm32-unknown-unknown/release', `${pkg}.wasm`)
  const bytes = readFileSync(wasmPath)
  mkdirSync(outDir, { recursive: true })
  const outFile = resolve(outDir, `${name}.bytes.ts`)
  writeFileSync(
    outFile,
    `// AUTO-GENERATED by scripts/build-wasm.mjs — do not edit.\nexport const wasmBase64 =\n  '${bytes.toString('base64')}'\n`,
  )
  try {
    execFileSync('npx', ['oxfmt', outFile], { cwd: root, stdio: 'ignore' })
  } catch {
    // formatting is best effort; format:check will catch a real problem
  }
  console.log(
    `built wasm/${name} (${pkg}.wasm, ${bytes.length} bytes) -> src/dsp/wasm/${name}.bytes.ts`,
  )
}

const args = process.argv.slice(2)
if (args.length === 0) {
  console.error('usage: node scripts/build-wasm.mjs <crate>|--all')
  process.exit(1)
}
const names =
  args[0] === '--all'
    ? readdirSync(wasmDir, { withFileTypes: true })
        .filter((e) => e.isDirectory() && existsSync(resolve(wasmDir, e.name, 'Cargo.toml')))
        .map((e) => e.name)
        .toSorted()
    : args
for (const name of names) build(name)
