#!/usr/bin/env node
/**
 * Build one or all Rust DSP kernels to wasm32 and embed the binary as a base64
 * TypeScript module so it can be loaded synchronously in workers, tests and the
 * browser without any asset/fetch plumbing.
 *
 * Each crate is built twice:
 *  - the default single-thread kernel on stable, embedded as `<crate>.bytes.ts`;
 *  - if the crate declares a `threads` feature, a Rayon-enabled kernel on a
 *    pinned nightly (`-Z build-std`) through `wasm-bindgen --target web`, emitted
 *    to `src/dsp/wasm/pkg/` so Vite can bundle the thread-pool worker.
 *
 * Usage:
 *   node scripts/build-wasm.mjs <crate>   # build wasm/<crate>
 *   node scripts/build-wasm.mjs --all     # build every wasm/* crate
 *
 * Requires the `wasm-bindgen` CLI matching the `wasm-bindgen` crate version on
 * PATH (or `WASM_BINDGEN=/path/to/wasm-bindgen`) for the threaded build, plus
 * `rustup toolchain install nightly-2025-11-15 --component rust-src`.
 */

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const wasmDir = resolve(root, 'wasm')
const outDir = resolve(root, 'src/dsp/wasm')
const targetDir = resolve(wasmDir, 'target')
const wasmOpt = resolve(root, 'node_modules/.bin/wasm-opt')
const THREAD_TOOLCHAIN = 'nightly-2025-11-15'

const SIMD_FLAG = '-C target-feature=+simd128'
const THREAD_FLAGS = [
  '-C target-feature=+simd128,+atomics,+bulk-memory',
  '-C link-arg=--shared-memory',
  '-C link-arg=--max-memory=1073741824',
  '-C link-arg=--import-memory',
  '-C link-arg=--export=__wasm_init_tls',
  '-C link-arg=--export=__tls_size',
  '-C link-arg=--export=__tls_align',
  '-C link-arg=--export=__tls_base',
].join(' ')

function rustFlags(extra = '') {
  const existing = process.env.RUSTFLAGS ?? ''
  const parts = [existing, SIMD_FLAG, extra].filter(Boolean)
  return parts.join(' ')
}

function crateName(dir) {
  const manifest = readFileSync(resolve(dir, 'Cargo.toml'), 'utf8')
  const match = manifest.match(/^\s*name\s*=\s*"([^"]+)"/m)
  if (!match) throw new Error(`no package name in ${dir}/Cargo.toml`)
  return match[1]
}

function hasThreadsFeature(dir) {
  const manifest = readFileSync(resolve(dir, 'Cargo.toml'), 'utf8')
  return /^\s*threads\s*=/m.test(manifest) || /^\s*threads\s*=\s*\[/m.test(manifest)
}

function wasmBindgenBin() {
  const bin = process.env.WASM_BINDGEN ?? 'wasm-bindgen'
  try {
    const version = execFileSync(bin, ['--version'], { encoding: 'utf8' }).trim()
    return { bin, version }
  } catch {
    throw new Error(
      `wasm-bindgen CLI not found (looked for "${bin}").\n` +
        `Install the matching version, e.g. cargo install wasm-bindgen-cli --version <crate version>,\n` +
        `or set WASM_BINDGEN to the binary path.`,
    )
  }
}

function optimize(wasmPath, { threads = false } = {}) {
  if (!existsSync(wasmOpt)) {
    console.warn(`wasm-opt not found at ${wasmOpt}; embedding unoptimized template`)
    return readFileSync(wasmPath)
  }
  const args = [
    wasmPath,
    '-O3',
    '--enable-simd',
    '--enable-bulk-memory',
    '--enable-nontrapping-float-to-int',
    '--strip-debug',
  ]
  if (threads) args.push('--enable-threads')
  const optimized = `${wasmPath}.opt.wasm`
  args.push('-o', optimized)
  execFileSync(wasmOpt, args, { stdio: 'inherit' })
  const bytes = readFileSync(optimized)
  rmSync(optimized, { force: true })
  return bytes
}

function build(name) {
  const dir = resolve(wasmDir, name)
  if (!existsSync(resolve(dir, 'Cargo.toml'))) {
    throw new Error(`unknown wasm crate: ${name}`)
  }
  execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown'], {
    cwd: dir,
    stdio: 'inherit',
    env: { ...process.env, CARGO_TARGET_DIR: targetDir, RUSTFLAGS: rustFlags() },
  })

  const pkg = crateName(dir)
  const wasmPath = resolve(targetDir, 'wasm32-unknown-unknown/release', `${pkg}.wasm`)
  const bytes = optimize(wasmPath)
  mkdirSync(outDir, { recursive: true })
  const outFile = resolve(outDir, `${name}.bytes.ts`)
  writeFileSync(
    outFile,
    `// AUTO-GENERATED by scripts/build-wasm.mjs — do not edit.\nexport const wasmBase64 =\n  '${bytes.toString('base64')}'\n`,
  )
  try {
    execFileSync('npx', ['oxfmt', outFile], { cwd: root, stdio: 'ignore' })
  } catch {
    // formatting is best effort; format:check will catch a real problem
  }
  console.log(
    `built wasm/${name} (${pkg}.wasm, ${bytes.length} bytes) -> src/dsp/wasm/${name}.bytes.ts`,
  )
}

function buildThreaded(name) {
  const dir = resolve(wasmDir, name)
  const pkg = crateName(dir)
  const { bin, version } = wasmBindgenBin()

  execFileSync(
    `cargo`,
    [
      `+${THREAD_TOOLCHAIN}`,
      'build',
      '--release',
      '--target',
      'wasm32-unknown-unknown',
      '--features',
      'threads',
      '-Z',
      'build-std=panic_abort,std',
    ],
    {
      cwd: dir,
      stdio: 'inherit',
      env: { ...process.env, CARGO_TARGET_DIR: targetDir, RUSTFLAGS: rustFlags(THREAD_FLAGS) },
    },
  )

  const wasmPath = resolve(targetDir, 'wasm32-unknown-unknown/release', `${pkg}.wasm`)
  const pkgDir = resolve(outDir, 'pkg')
  rmSync(pkgDir, { recursive: true, force: true })
  mkdirSync(pkgDir, { recursive: true })
  execFileSync(bin, ['--target', 'web', '--out-dir', pkgDir, '--out-name', name, wasmPath], {
    stdio: 'inherit',
  })
  writeFileSync(
    resolve(pkgDir, 'package.json'),
    `${JSON.stringify(
      {
        name: `webisdb-${name}-wasm`,
        version: '0.0.0',
        private: true,
        type: 'module',
        main: `./${name}.js`,
        module: `./${name}.js`,
        types: `./${name}.d.ts`,
      },
      null,
      2,
    )}\n`,
  )

  const bgWasm = resolve(pkgDir, `${name}_bg.wasm`)
  const optimized = optimize(bgWasm, { threads: true })
  writeFileSync(bgWasm, optimized)

  console.log(
    `built wasm/${name} threads (${version}) -> src/dsp/wasm/pkg/${name}.js + ${name}_bg.wasm`,
  )
}

const args = process.argv.slice(2)
if (args.length === 0) {
  console.error('usage: node scripts/build-wasm.mjs <crate>|--all [--threads]')
  process.exit(1)
}
const threadsOnly = args.includes('--threads')
const names =
  args[0] === '--all'
    ? readdirSync(wasmDir, { withFileTypes: true })
        .filter((e) => e.isDirectory() && existsSync(resolve(wasmDir, e.name, 'Cargo.toml')))
        .map((e) => e.name)
        .toSorted()
    : args.filter((a) => !a.startsWith('--'))
for (const name of names) {
  const dir = resolve(wasmDir, name)
  if (!threadsOnly) build(name)
  if (hasThreadsFeature(dir)) buildThreaded(name)
}
